{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{  .Values.adpulse.ad_server_svc.serviceAccountName }}
  labels:
    {{ .Values.adpulse.ad_server_svc.labels | toYaml | nindent 4}}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}