apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.adpulse.ad_server_svc.name }}
  namespace: {{ .Values.adpulse.namespace.name }}
  labels:
    {{ .Values.adpulse.ad_server_svc.labels | toYaml | nindent 4}}
spec:
  replicas: {{ .Values.adpulse.ad_server_svc.replicaCount }}
  selector:
    matchLabels:
      {{ .Values.adpulse.ad_server_svc.selectorLabels | toYaml | nindent 6}}
  template:
    metadata:
      labels:
        {{ .Values.adpulse.ad_server_svc.selectorLabels | toYaml | nindent 8}}
    spec:
      serviceAccountName: {{ .Values.adpulse.ad_server_svc.serviceAccountName }}
      containers:
        - name: {{ .Values.adpulse.ad_server_svc.name }}
          image: "{{ .Values.adpulse.ad_server_svc.image.repository }}:{{ .Values.adpulse.ad_server_svc.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: AD_MANAGER_ADDRESS
              value: {{ .Values.ad_manager_url }}
            - name: RENDER_URL
              value: {{ .Values.ad_engagement_svc_rndr}}
            - name: CLICK_URL
              value: {{ .Values.ad_engagement_svc_clk }}
          ports:
            - name: http
              containerPort: {{ .Values.adpulse.ad_server_svc.service.port }}
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /health
          #     port: http